---
tags:
  - name: sourcetype
    pattern: "(eeg|eyetrack|mri|nirs|genome)"
  - name: subject
    pattern: "[/\\\\]+sub-([a-zA-Z0-9]+)"
  - name: session
    pattern: "[_/\\\\]+ses-([a-zA-Z0-9]+)"
  - name: task
    pattern: "[_/\\\\]+task-([a-zA-Z0-9]+)"
  - name: acquisition
    pattern: "[_/\\\\]+acq-([a-zA-Z0-9]+)"
  - name: run
    pattern: "[_/\\\\]+run-([0-9]+)"
  - name: suffix
    pattern: "(?:^|[_/\\\\])([a-zA-Z0-9]+)\\.[^/\\\\]+$"
  - name: extension
    pattern: "[^./\\\\](\\.[^/\\\\]+)$"
path_patterns:
  - "{sourcetype<mri>|mri}/sub-{subject}[/ses-{session}]/sub-{subject}[_ses-{session}][_task-{task}][_acq-{acquisition}][_run-{run}]_{suffix<mri>|mri}{extension<.dcm>}"  
  - "{sourcetype<eeg>|eeg}/sub-{subject}[/ses-{session}]/sub-{subject}[_ses-{session}]_task-{task}[_acq-{acquisition}][_run-{run}]_{suffix<eeg>|eeg}{extension<.bdf|.cnt|.eeg|.edf|.data|.gdf|.mat|.mff|.nxe|.set|.vhdr|.vmrk>}"  
  - "{sourcetype<nirs>|nirs}/sub-{subject}[/ses-{session}]/sub-{subject}[_ses-{session}]_task-{task}[_acq-{acquisition}][_run-{run}]_{suffix<nirs>|nirs}{extension<.nirx>}"  
  - "{sourcetype<eyetrack>|eyetrack}/sub-{subject}[/ses-{session}]/sub-{subject}[_ses-{session}]_task-{task}[_acq-{acquisition}][_run-{run}]_{suffix<eyetrack>|eyetrack}{extension<.edf|.dat|.log>}"
